name: Desktop app release

on: [push]

jobs:

  build-binaries:
    name: Build ${{ matrix.config.os }} @ ${{ matrix.config.arch }}
    runs-on: ${{ matrix.config.os }}
    # if: startsWith(github.ref, 'refs/tags/')
  
    strategy:
      matrix:
        config:
          - os: windows-latest
            arch: x64
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
  
      - name: Install Frontend Dependencies
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        run: |
          yarn
        shell: bash

      - name: Build, package and make
        run: |
          yarn make --arch=${{ matrix.config.arch }}
        env:
          APP_VERSION: "0.1.100"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-windows
          path: out/make/**/*
  publish-to-github:
    needs: [build-binaries]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download amd64 artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: "create release"
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_name: "0.1.100"
          prerelease: false
          generate_release_notes: true
          files: ./artifacts/artifacts-*/**/*
